name: Deploy Runner

permissions:
  id-token: write
  contents: read

on: workflow_dispatch
  # push:
  #   branches:
  #   - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy_runner_stack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
    - name: Setup Node.js environment
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
      with:
        node-version: 22
        cache: "npm"        
    - name: Install dependencies
      run: npm ci        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a  # v4
      with:
        role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
        aws-region: ${{ vars.AWS_TARGET_REGION }}
    - name: cdk synth
      uses: tj-actions/aws-cdk@e9c2b94df8f54b99318ba2728331a54c081874b0  # v4
      with:
        cdk_subcommand: "synth"
        cdk_stack: "ChromiumBuilderStack"
    - name: Deploy RunnerStack (via CDK)
      uses: tj-actions/aws-cdk@e9c2b94df8f54b99318ba2728331a54c081874b0  # v4
      with:
        cdk_subcommand: "deploy"
        cdk_stack: "ChromiumBuilderStack"
        cdk_extra_args: >-
          --progress events
          --require-approval never
          --parameters environment=${{ secrets.ENVIRONMENT }}